### ISSUE TITLE
Display both compressed and uncompressed diffs in report

### ISSUE THREAD

**Issue by rpiaggio** [LironEr/bundlemon#46]
Alternatively, the ability to use an alternate config file from the GH action. Then, we could run bundlemon twice, one with compression and one without.

**Comment by LironEr** [comment]
@rpiaggio sorry for the long wait

I decided not to solve this issue by displaying both compressed and uncompressed because this change would require a lot of changes to the current code and might make things more difficult, will try to think about that in the feature.

So the other solution is to use the "subproject" feature which is available in [v1.3.0](https://github.com/LironEr/bundlemon/releases/tag/bundlemon%40v1.3.0)

```sh
yarn run bundlemon # assuming you are using default compression as gzip in your config file
yarn run bundlemon --subProject no-compression --defaultCompression none
```

or

```sh
yarn run bundlemon --subProject gzip-compression --defaultCompression gzip
yarn run bundlemon --subProject no-compression --defaultCompression none
```

Assuming you set Github output with comment & status this will create 2 comments and 2 statuses, one for each subproject.

Hope this solves the issue, if it does please close the issue,if not please let me know what I can do to help you (:
